spring:
  rabbitmq:
    port: 5672

rest-api:
  host: http://localhost:8080

rabbitmq:
    producer:
      telegram-notifications-queue: telegram-notifications-queue
    consumer:
      new-vacancies-queue: new-vacancies-queue